version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: chikaturin
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
