name: Fetch Voucher API at Midnight

on:
  schedule:
    - cron: "0 0 * * *" # Chạy mỗi ngày vào 0:00 giờ UTC

jobs:
  fetch-api:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Voucher API
        run: |
          curl -X GET https://server-voucher.vercel.app/api/VoucherWithDate
